version: "3.8"

services:
    mysql:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        tty: true
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - ./backend/storage/docker/mysql:/var/lib/mysql

    backend:
        build:
            context: ./backend
            dockerfile: docker/php/Dockerfile
        container_name: backend
        restart: unless-stopped
        tty: true
        working_dir: /var/www/backend
        ports:
            - '9000:9000'
        volumes:
            - ./backend:/var/www/backend

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - '80:80'
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/logs:/var/log/nginx/
            - ./backend:/var/www/backend
            - ./frontend:/var/www/frontend